# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://citieo.com
title: Citieo
email: support@citieo.com
author: Citieo LLC
description: > # "Write an awesome description for your new site here. 
  Citieo. Helping small cities.
copyright: 'Copyright &copy; 2019 Citieo LLC. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://facebook.com/citieo
  - title: email
    url: support@citieo.com
